server:
  port: 9092
 
  
  
spring:
  datasource:
    url: jdbc:h2:mem:employee-db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: sa

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console:
      path: /db-console
  application:
    name: employee-application

logging:
  level:
    com.netflix.eureka: OFF
    com.netflix.discovery: OFF
  
eureka:
  instance:
    appname: employee-application
  client:
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
              